aulaszeus/admin/controllers.py
# -*- coding: utf-8 -*-
"""
    aulaszeus.admin.controllers
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    aulaszeus admin controllers module

    :copyright: (c) 2016 by Haynesss.
    :license: BSD, see LICENSE for more details.
"""
from flask import current_app, render_template, Blueprint, jsonify
from flask.ext.security import roles_required
from aulaszeus.users import models

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@roles_required('admin')
@blueprint.route('/users')
def get_users():
    """return users in admin."""
    current_app.logger.debug(u'Get all users in admin.')
    users = models.User.objects()
    return render_template('admin/users/list.html', users=users)

@roles_required('admin')
@blueprint.route('/')
def admin_page():
    """return users in admin."""
    current_app.logger.debug(u'Get all users in admin.')
    return render_template('admin/index.html')

@roles_required('admin')
@blueprint.route('/users/active/<pk>')
def active_user(pk):
    """."""
    user = models.User.objects.get_or_404(pk=pk)
    if user.active:
        user.active = False
    else:
        user.active = True
    user.save()
    return jsonify(data=user.active)

templates/security/_menu.html
<ul class="nav navbar-nav navbar-right">
    {%- if current_user.is_authenticated -%}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            Oi {{ current_user.fullname }} <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ url_for('users.profile') }}">Perfil</a></li>
            {% if current_user.has_role('admin') -%}
            <li role="separator" class="divider"></li>
            <li><a href="{{ url_for('admin.admin_page') }}">Administração</a></li>
            {% endif -%}
            <li role="separator" class="divider"></li>
            <li><a href="{{ url_for('security.logout') }}">Sair</a></li>
        </ul>
    </li>
    {%- else -%}
        {% if security.registerable %}
        <li><a href="{{ url_for('security.register') }}">Registrar</a></li>
        {% endif %}
        <li>
        <a href="{{ url_for('security.login') }}">Login</a>
        </li>
    {%- endif -%}
</ul>

templates/security/forgot_password.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "security/index.html" %}

{% block title %}
Restar Senha
{% endblock %}

{% block form_content %}
<h1>Adicione o email para resetar sua senha</h1>
<form action="{{ url_for('security.forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ wtf.form_field(forgot_password_form.email) }}
  {{ wtf.form_field(forgot_password_form.submit, class_="btn") }}
</form>

{% endblock %}

templates/security/index.html
{% extends "base.jinja" %}

{% block title %}
Autenticação
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
    		{{ content }}
            {% block form_content %}{% endblock %}
        </div>
        <div class="col-xs-4"></div>
    </div>
</div>
{% endblock %}

templates/security/login_user.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "security/index.html" %}

{% block title %}
Login
{% endblock %}

{% block form_content %}
<h1>Login</h1>
<form action="{{ url_for('security.login') }}" method="POST" name="register_user_form">
    {{ login_user_form.hidden_tag() }}

    {{ wtf.form_errors(login_user_form) }}

    {{ wtf.form_field(login_user_form.email) }}
    {{ wtf.form_field(login_user_form.password) }}
    {{ wtf.form_field(login_user_form.remember) }}
    {{ wtf.form_field(login_user_form.submit) }}
    <a href="{{ url_for('security.forgot_password') }}">Esqueceu a senha</a>

</form>
{% endblock %}

templates/security/register_user.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "security/index.html" %}

{% block title %}
Registrar
{% endblock %}

{% block form_content %}
    <h1>Registrar</h1>
    <form action="{{ url_for('security.register') }}" method="POST" name="register_user_form" novalidate>
        {{ register_user_form.hidden_tag() }}

        {{ wtf.form_field(register_user_form.fullname) }}
        {{ wtf.form_field(register_user_form.email) }}
        {{ wtf.form_field(register_user_form.password) }}
        {% if register_user_form.password_confirm %}
            {{ wtf.form_field(register_user_form.password_confirm) }}
        {% endif %}
        {{ wtf.form_field(register_user_form.submit) }}

    </form>
{% endblock %}

templates/security/reset_password.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "security/index.html" %}

{% block title %}
Redefinir Senha
{% endblock %}

{% block form_content %}
<h1>Redefinir senha</h1>
    <form action="{{ url_for('security.reset_password', token=reset_password_token) }}" method="POST" name="register_user_form">
        {{ reset_password_form.hidden_tag() }}

        {{ wtf.form_errors(reset_password_form) }}

        {{ wtf.form_field(reset_password_form.password) }}
        {{ wtf.form_field(reset_password_form.password_confirm) }}
        {{ wtf.form_field(reset_password_form.submit) }}

    </form>
{% endblock %}