aulaszeus/users/models.py
# -*- coding: utf-8 -*-
"""
    aulaszeus.users.models
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    aulaszeus user models module

    :copyright: (c) 2016 by Haynesss.
    :license: BSD, see LICENSE for more details.
"""
from flask import current_app

from flask_security import UserMixin, RoleMixin


from mongoengine import *
from mongoengine import signals
from mongoengine import fields

from aulaszeus.extensions import db


class Role(db.Document, RoleMixin):
    """Roles."""
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)


class Address(db.EmbeddedDocument):
    """ endereco usuario """
    tipo = db.StringField()
    endereco = db.StringField()
    cidade = db.StringField()
    estado = db.StringField()
    bairro = db.StringField()
    complemento = db.StringField()
    cep = db.StringField()
    numero = db.StringField()


class User(db.DynamicDocument, UserMixin):
    """User."""
    email = db.StringField(max_length=255)
    fullname = db.StringField()
    username = db.StringField(max_length=255)
    password = db.StringField(max_length=255)
    active = db.BooleanField(default=False)
    confirmed_at = db.DateTimeField()
    roles = db.ListField(db.ReferenceField(Role), default=[])
    current_login_at = db.DateTimeField()
    current_login_ip = db.StringField()
    last_login_at = db.DateTimeField()
    last_login_ip = db.StringField()
    login_count = db.IntField()
    avatar = db.StringField()
    imagem = db.ImageField(size=(800, 800, True),
        thumbnail_size=(84, 84, True))
    endereco = db.EmbeddedDocumentField(Address, default=Address)

    @property
    def id(self):
        """Return id."""
        return self.pk

    @classmethod
    def by_email(cls, email):
        """Find user by email."""
        return cls.objects(email=email).first()

    @property
    def gravatar(self):
        """Get gravatar."""
        email = self.email.strip()
        email = email.encode("utf-8")
        import hashlib
        encoded = hashlib.md5(email).hexdigest()
        return "https://secure.gravatar.com/avatar/%s.png" % encoded

    @classmethod
    def pre_save(cls, sender, document, **kwargs):
        """Save user and put role user."""
        if len(document.roles) == 0:
            role = Role.objects.get(name='user')
            document.roles = [role]

    def __unicode__(self):
        """return object with email."""
        return "{}".format(self.email)


signals.pre_save.connect(User.pre_save, sender=User)

aulaszeus/users/forms.py
# -*- coding: utf-8 -*-
"""
    aulaszeus.users.forms
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

    aulaszeus user forms module

    :copyright: (c) 2016 by Haynesss.
    :license: BSD, see LICENSE for more details.
"""
from flask_wtf import Form
from wtforms import StringField, BooleanField, PasswordField, SubmitField, \
    FileField, FormField
from wtforms.validators import DataRequired, Email, Length, EqualTo, \
    ValidationError
from flask_security.forms import ConfirmRegisterForm, LoginForm

class CustomLoginForm(LoginForm):
    """Custom LoginForm"""
    email = StringField("Email")
    password = PasswordField("Senha")
    remember = BooleanField("Lembre-se de mim")

class ExtendedRegisterForm(ConfirmRegisterForm):
    """Custom Register Form."""
    fullname = StringField("Nome Completo", validators=[DataRequired(message="O nome Completo é obrigatório")])
    email = StringField("Email", validators=[Email("E-mail é obrigatório")])
    password = PasswordField("Senha", validators=[Length(min=6, max=20,
        message="A senha deve conter de %(min)d á %(max)d caracteres | Dica: Utilize letras, numeros e simbolos" )])
    submit = SubmitField("Registrar")

class AddressRegisterForm(Form):
    tipo = StringField()
    endereco = StringField()
    cidade = StringField()
    estado = StringField()
    bairro = StringField()
    complemento = StringField()
    cep = StringField()
    numero = StringField()

class ProfileForm(Form):
    imagem = FileField('Imagem')
    fullname = StringField('Nome Completo')
    username = StringField('Username')
    endereco = FormField(AddressRegisterForm, default=lambda: {})
    submit = SubmitField("Enviar Dados")

    """def validate_endereco(form, field):
        field.data = {}

    def validate_image(form, field):
        if field.data:
            field.data = re.sub()"""

aulaszeus/users/__init__.py
# -*- coding: utf-8 -*-
"""
    aulaszeus.users
    ~~~~~~~~~~~~~~~~~~~~~

    aulaszeus user module

    :copyright: (c) 2016 by Haynesss.
    :license: BSD, see LICENSE for more details.
"""
from . import controllers

aulaszeus/users/controllers.py
# -*- coding: utf-8 -*-
"""
    aulaszeus.users.controllers
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    aulaszeus user controllers module

    :copyright: (c) 2016 by Haynesss.
    :license: BSD, see LICENSE for more details.
"""
from flask import current_app, render_template, Blueprint, request, flash, \
    redirect, send_file, url_for
from flask_security import login_required, current_user
from flask_wtf import Form
from aulaszeus.users import forms, models

blueprint = Blueprint('users', __name__, url_prefix='/users')

@blueprint.route('/profile')
@login_required
def profile():
    """return user profle."""
    current_app.logger.debug(u'Get profile user.')
    return render_template('users/profile.html')

@blueprint.route('/profile/edit', methods=["GET", "POST"])
@login_required
def profile_edit():
    current_app.logger.debug(u'User Profile Edit.')
    form = forms.ProfileForm(obj=current_user)

    if form.validate_on_submit():
        instance = models.User.objects.get(pk=current_user.pk)
        image_data = request.files.get(form.imagem.name)
        if image_data:
            if instance.imagem:
                instance.imagem.delete()
            instance.imagem.put(image_data)
            del form.imagem
        else:
            del form.imagem

        form.populate_obj(instance)
        instance.save()
        flash('Perfil Atualizado com sucesso!', 'success')
        return redirect(url_for("users.profile"))

    return render_template('users/edit.profile.html', form=form)

@blueprint.route('/profile/image', methods=["GET", "POST"])
@login_required
def profile_image():
    instace = models.User.objects.get_or_404(pk=current_user.pk)
    return send_file(instace.imagem.thumbnail, mimetype='image')

templates/users/edit.profile.html
{% extends "base.jinja" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block title %}
Edição de Perfíl
{% endblock %}

{% block content %}
<div class="container">
    <p>
    {% if current_user.imagem %}
        <img class="img-circle" alt="Avatar" src="{{ url_for('users.profile_image') }}">
    {% else %}
        <img class="img-circle" alt="Avatar" src="{{ current_user.gravatar }}">
    {% endif %}</p>
    <p><b>Email:</b> {{current_user.email}}</p>
    <p><b>Ultimo Acesso:</b> {{current_user.last_login_at.strftime("%d/%m/%Y")}}</p>

    <form action="{{ url_for('users.profile_edit')}}" method="post"
        enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        {{ form.endereco.hidden_tag() }}
        {{ wtf.form_field(form.imagem) }}
        {{ wtf.form_field(form.fullname) }}

        {{ wtf.form_field(form.endereco.cep) }}
        {{ wtf.form_field(form.endereco.tipo) }}
        {{ wtf.form_field(form.endereco.endereco) }}
        {{ wtf.form_field(form.endereco.bairro) }}
        {{ wtf.form_field(form.endereco.numero) }}
        {{ wtf.form_field(form.endereco.cidade) }}
        {{ wtf.form_field(form.endereco.estado) }}
        {{ wtf.form_field(form.endereco.complemento) }}
        {{ wtf.form_field(form.submit, class="btn btn-success raised")}}
    </form>
    <br>
</div>
{% endblock %}

templates/users/profile.html
{% extends "base.jinja" %}

{% block title %}
Perfíl
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3 text-center">
            <img class="img-circle img-responsive" src="{{url_for('users.profile_image')}}"/>
        </div>
        <div class="col-md-9">
            <p><b>Nome: </b>{{current_user.fullname}}</p>
            <p><b>Email: </b>{{ current_user.email }}</p>
            <p><b>Último Acesso: </b>{{ current_user.last_login_at.strftime("%d/%m/%Y") }}</p>
            <p><b>Admitido em: </b> {{ current_user.confirmed_at }} </p>
            <p><b>Você se logou:</b> {{current_user.login_count}} vezes</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 right">
            <a href="{{ url_for('users.profile_edit') }}" class="btn btn-info">Editar Perfil</a>
        </div>
    </div>
</div>
{% endblock %}